### ISSUE TITLE
Use reverse engineered "deep link" just like Google does

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/fares-service#4]
https://www.google.de/maps/dir/71083+Herrenberg/Stuttgart/@48.684776,8.8829129,11z/am=t/data=!4m14!4m13!1m5!1m1!1s0x479758c2ddc44031:0x41ffd3c8d0927b0!2m2!1d8.8671577!2d48.5950369!1m5!1m1!1s0x4799db34c1ad8fd3:0x79d5c11c7791cfe4!2m2!1d9.1829321!2d48.7758459!3e3

![Screenshot from 2021-06-10 17-41-11](https://user-images.githubusercontent.com/151346/121555431-4bcf5380-ca13-11eb-8dac-1936ab5b805a.png)

It should just send you to the VVS ticket shop.

**Comment by derhuerst** [comment]
The Docker image is now published, its digest is `0c9de92ea7fe`.
