### ISSUE TITLE
No price info from Ehningen to Nufringen

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/fares-service#5]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Ehningen%3A%3A48.6592556%2C8.9405097/Nufringen%3A%3A48.6224388%2C8.8881021/0?time=1624876708

**Comment by derhuerst** [comment]
For me, both itineraries have a price. Can you clarify @leonardehrenfried?

**Comment by leonardehrenfried** [comment]
Strange, cannot reproduce anymore.
